FROM  node:16.13.1

WORKDIR /The-Record-box/src

ENV PORT 4200

EXPOSE 8888

COPY package.json /The-Record-box/package.json

RUN npm install

COPY . /The-Record-box/src/app

CMD [ "node", "src/index.html" ]
